name: hayward-boltz2
channels:
  - conda-forge
dependencies:
  - python=3.10
  - biopython=1.85
  - numpy=1.26.0
  - openpyxl=3.1.5
  - pandas=2.2.3
  - rdkit=2024.09.5
  - requests=2.32.2
  - scipy=1.15.2
  - pip
  - pip:
      - posebusters==0.4.6
